name: CI Develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Passo 1: Baixar dependências
      - name: Install dependencies
        run: npm install

      # Passo 2: Executar testes
      - name: Run tests
        run: npm test